# Generated by Django 4.1.7 on 2023-04-06 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MultipleImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="markdown_pics"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("short_intro", models.CharField(max_length=300)),
                ("content", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task_performance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("blocked", "Not Available"),
                            ("available", "Available"),
                            ("inProgress", "In Progress"),
                            ("waiting", "Waiting"),
                            ("completed", "Completed"),
                        ],
                        default="blocked",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not-graded", "Not Graded"),
                            ("passed", "Passed"),
                            ("redo", "Redo"),
                        ],
                        default="not-graded",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "github_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "submit_file",
                    models.FileField(blank=True, null=True, upload_to="uploads"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
