# Generated by Django 4.1.7 on 2023-04-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.profile",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="my_tracks", to="user.profile"
            ),
        ),
        migrations.AddField(
            model_name="task_performance",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
            ),
        ),
        migrations.AddField(
            model_name="task_performance",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.task",
            ),
        ),
        migrations.AddField(
            model_name="task_performance",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="prerequisite",
            field=models.ManyToManyField(blank=True, to="tracks.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="multipleimage",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.task",
            ),
        ),
        migrations.AddField(
            model_name="assessors",
            name="task_performance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.task_performance",
            ),
        ),
        migrations.AddField(
            model_name="assessors",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="assessors",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
            ),
        ),
    ]
