# Generated by Django 4.1.7 on 2023-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0004_track_short_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="short_intro",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
