# Generated by Django 4.1.7 on 2023-04-13 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("tracks", "0005_alter_track_short_intro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task_assessor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "task_performance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracks.task_performance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track_assessor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.profile",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracks.track",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Assessors",
        ),
        migrations.AddField(
            model_name="task_assessor",
            name="track_assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track_assessor",
            ),
        ),
    ]
