# Generated by Django 4.1.7 on 2023-04-13 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0006_task_assessor_track_assessor_delete_assessors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="track",
            name="category",
            field=models.ManyToManyField(related_name="tracks", to="tracks.category"),
        ),
    ]
