# Generated by Django 4.1.7 on 2023-04-16 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("tracks", "0008_track_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track_review",
            old_name="profile",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="track_review",
            unique_together={("owner", "track")},
        ),
    ]
