# Generated by Django 4.1.7 on 2023-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0010_remove_task_performance_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task_assessor",
            name="comment",
        ),
        migrations.AddField(
            model_name="task_performance",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
