# Generated by Django 4.1.7 on 2023-05-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0012_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(
                default="certificate_template.jpg", upload_to="certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="multipleimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/markdown_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="task_performance",
            name="submit_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
