# Generated by Django 4.1.7 on 2023-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0013_alter_certificate_file_alter_multipleimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(default="certificate_template.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="multipleimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="markdown_pics"),
        ),
        migrations.AlterField(
            model_name="task_performance",
            name="submit_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
