# Generated by Django 4.1.7 on 2023-04-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="session_key",
            field=models.TextField(null=True),
        ),
    ]
