# Generated by Django 4.1.7 on 2023-04-26 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_session_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-created"]},
        ),
    ]
