# Generated by Django 4.1.7 on 2023-05-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_pics/user-default.png",
                null=True,
                upload_to="images/profile_pics/",
            ),
        ),
    ]
