# Generated by Django 4.1.7 on 2023-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_pics/user-default.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
